### ISSUE TITLE
Notice: session_start()

### ISSUE THREAD

**Issue by bsoliveira** [bryanjhv/slim-session#14]
Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /home/vagrant/Code/slim/vendor/bryanjhv/slim-session/src/Slim/Middleware/Session.php on line 110

Slim 3
PHP 7.1.2-3+
Linux homestead 4.4.0-51-generic #72-Ubuntu 

config:
	'lifetime':  '30 minutes',
        'path' :  '/',
        'domain':  NULL,
        'secure' :  FALSE,
        'httponly' : FALSE,
        'name' :  'slim_session',
        'autorefresh' : FALSE

Suggestion: http://stackoverflow.com/questions/22215173/session-error-permisison-denied-13

Hello! Would have some way to deploy the option to configure these ini_set('session.gc_probability', 0)?

**Comment by bryanjhv** [comment]
Please tell which server are you using (Homestead may use Apache or Nginx), and this problem usually happens when using Apache.

It's clearly a permissions issue, maybe you need to `chmod -R :www-data` your files; setting `gc_probability` to 0 tells PHP: *never clear session files*, which you don't probably want.

P.S.: maybe it helps you decide: http://serverfault.com/questions/330492/php-session-start-permisson-denied

**Comment by bsoliveira** [comment]
I'm using Nginx, I'll see this permissions tip. Really do not wipe the session files is not interesting. thank you so much!

**Comment by bryanjhv** [comment]
Advice me if you got a solution, if not I'll need to retake on #7.

**Comment by bsoliveira** [comment]
I agree with you. Thank you
