### ISSUE TITLE
Can I store user information to maintain user session without concerns?

### ISSUE THREAD

**Issue by jvitoroc** [bryanjhv/slim-session#23]
I get the userid from the DB and store it in the session so then I can authenticate the user, should I be worried?

**Comment by bryanjhv** [comment]
Well, this module is just a wrapper for **native** PHP sessions, so if you do that while manipulating `$_SESSION`, then you can do it with this module.

AFAIK, I store just the `userId` and other metadata in the session, not entire user information. Some systems limit the size of session data, so to prevent a crash or something it's better to just store that.

**Comment by jvitoroc** [comment]
> _AFAIK, I store just the userId and other metadata in the session, not entire user information. Some systems limit the size of session data, so to prevent a crash or something it's better to just store that._

@bryanjhv This is exactly what I'm doing, but I'm worried if it's secure or not. In some way a bad user get to change the userid of the session cookie and get full access to other user account.

_English is not my first languague :/_

**Comment by bryanjhv** [comment]
What's stored in the session cookie is the session's own ID (in the server), not the data itself. The data is stored server-side in files, so the most thing a bad user can do is change the session cookie to one that expired, which in that case should log out your current user (because session is no longer being used).

If you're worried, you can encrypt session data, but I'm waiting integration for #21, where `ezimuel/php-secure-session` comes into party. @Danack, any advance on this topic?
