### ISSUE TITLE
Cannot change session settings when session is active

### ISSUE THREAD

**Issue by juliardi** [bryanjhv/slim-session#41]
I've got this message when using this library :
```
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in vendor\bryanjhv\slim-session\src\Slim\Middleware\Session.php on line 132
```
It might be better to check if the session is active before calling `ini_set()`

**Comment by bryanjhv** [comment]
I think I should update the README stating that this module manages everything about sessions so you **shouldn't call `session_start` at any time**. Will update docs soon.

**Comment by bryanjhv** [comment]
Sorry, button misclick.

`session_start` should not be called outside because this module also makes other method calls meant for the features it provides, as you can see at:

https://github.com/bryanjhv/slim-session/blob/0205470a35c716823ededae04d84a7f27fba400a/src/Slim/Middleware/Session.php#L84-L126

Calling `session_start` alone would be the same as only using the `Helper` (not the middleware).

**Comment by juliardi** [comment]
Thank you for the answer. I found that my `public/index.php` contains a `session_start()` call while also using the middleware in the route. After I delete that, the warning disappeared.
