### ISSUE TITLE
SameSite Cookie Parameter Support

### ISSUE THREAD

**Issue by sundayz** [bryanjhv/slim-session#54]
Hi,

As of Chrome 76 and Firefox 69, a new cookie parameter called SameSite has been added. Currently it is disabled by default in Firefox 76 and Chrome 80, but when it is enabled, any cross site cookies that do not include this parameter will be rejected. Currently Firefox 76 emits a warning about such cookies, and Chrome 81 should too but in my tests it's already rejecting them, but I can't confirm if that is really the case.

There are 3 values allowed for SameSite: `None`, `Lax`, `Strict`.

**None**
Cookies with `SameSite=None` MUST also have the Secure parameter set or they will be rejected. This means that the browser will reject cross-site cookies over HTTP connections.

**Lax**
Cookies with no SameSite specified are treated as if they are using `Lax`. Cookies with `SameSite=Lax` are only sent on same-site requests, OR cross site requests with a safe method, for example GET.

**Strict**
Cookies with `SameSite=Strict` will never be sent for cross site requests, for example when someone follows an `<a href="...">` link to your site from an email or another site.

Now here is a problem:
Before PHP version 7.3, [a bug in the cookie validation code ](https://github.com/php/php-src/commit/5cb825df7251aeb28b297f071c35b227a3949f01) allows us to add the SameSite parameter through the domain or path parameters. For example 'path' => '/; SameSite=Lax'. That bug is fixed in 7.3 and an `array $options` is added to the cookie setting functions where SameSite can be set as a key => value.

I forked this repo and I'm working on a fix. If you want to keep support for < 7.3, I can send a PR with the fix, which looks something like this:

```php
        if (PHP_VERSION_ID >= 70300) {
            session_set_cookie_params([
                'lifetime' => $settings['lifetime'],
                'path' => $settings['path'],
                'domain' => $settings['domain'],
                'secure' => $settings['secure'],
                'httponly' => $settings['httponly'],
                'samesite' => $settings['samesite'],
            ]);
        } else {
            session_set_cookie_params(
                $settings['lifetime'],
                $settings['path'] . "; SameSite={$settings['samesite']}",
                $settings['domain'],
                $settings['secure'],
                $settings['httponly']
            );
        }
```

If you're not interested in supporting PHP < 7.3, the fix is easy, just use the new session_set_cookie_params and setcookie versions which take an array and accept an array and set 'samesite' there. 

**More info:**
https://web.dev/samesite-cookies-explained/
https://github.com/GoogleChromeLabs/samesite-examples/blob/master/php.md

**Comment by bryanjhv** [comment]
Hi! Thanks for the update!

After reading some articles, I have a few questions in order to correctly implement this without breaking applications, browsers, etc.:

- [Browser support](https://caniuse.com/#feat=same-site-cookie-attribute) is a bit recent (in many countries you find Firefox 56 or Chrome 49 in computer/school devices, also Android 4.4). I think support should depend on the users of this library.
- Plan here is to also support Slim 2, there's a need to support PHP 5.3. Users shouldn't feel forced to upgrade their entire codebase to Slim 4.
- Thanks for pointing out the bug part, I was about to suggest to just use the same call for all PHP versions.

Said that, here are some ideas I can think of:

- Allow `samesite` key in `$settings` but with this signature:
  ```php
  $settings['samesite'] == false     // keep current, make default?
  $settings['samesite'] == true      // set best option but which one?
                                     // if best==none, account for !secure
  $settings['samesite'] == 'string'  // power user, just set it's value
  ```
  This would make this an opt-in, which users can take in order to not break their current app users. They can enable it in case they don't care about breaking them or their users just use supported browsers.
- Keep support for PHP down to 5.3 and backport the change to 2.x, 3.x and 4.x.
- Maybe require a package for browser support detection, would work best to not break anything but might annoy conservative developers. And might use user-agent sniffing (I guess) which I don't like very much, but that isn't useful here.

**Comment by sundayz** [comment]
You’re right, it looks like we’ll need to do user agent sniffing. Here is Chromiums example for how to do it. We’ll probably have to implement this ourselves in PHP unless someone has already done it. 

https://www.chromium.org/updates/same-site/incompatible-clients

In order to support PHP 5.6 I think we’ll have to manually set the cookie with the header() method? I’m not sure, luckily I don’t deal with a lot of 5.6 code :) In order to avoid a lot of if statements checking php version maybe we can use header() everywhere, even though I’m not the biggest fan of doing that.

I think your suggestion for the samesite setting would work okay, I don’t see why not. It could be a bit confusing that the browser default for SameSite is “Lax”, while “false” might make the user think it would be None?

My personal use case is Slim 3 so I haven’t looked too much at the 2 and 4 branches.

**Comment by bryanjhv** [comment]
Looks like the user-agent sniffing part will take a lot of work, even if taking the data from [Can I use](https://caniuse.com/#feat=same-site-cookie-attribute) into account, and if done it should be made available via another package because that's not directly related to this one's purpose. Maybe not a viable option.

For the PHP < 7.3 part, I'm gonna guess we can take advantage of that bug you linked to in order to set that parameter. Or, better, is there any way to see which PHP versions a bugfix was applied to? I'm not such aware of the way PHP team handles those things, to be honest.

I haven't considered that specific case for dealing with `false` and `'none'` values, and I don't want users to keep looking at the README and fill it with lots of warnings, so maybe we can just take [Laravel's approach](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Cookie/CookieJar.php#L41) by defaulting it to `'lax'`.

I strive to keep all the branches with the same features, and the code is almost the same, except for the PHP version they rely on, so there's no problem regarding that.

Some thing I was thinking of is: how do non-supported browsers behave when sent the `samesite` parameter? Some scenarios (to test) might be:
- Take it as the cookie value: given this package only cares about session cookie, it could detect it when sent and strip that away.
- Emit some kind of warning or refuse to set the cookie: we're screwed up and a decision has to be made (supporting everyone by detecting support, or just let them screw up).
- Just ignore that parameter as unrecognized: just patch everything using the code you provided, and make a safe default to `'lax'`.

**Comment by sundayz** [comment]
Okay so I read the GoogleChromeLabs/samesite-examples link I posted again and this is what we're going to have to do:

For **session_set_cookie_params** which is the PHP session cookie, we use the new function in 7.3. In older versions we use the bug where we append samesite=Lax to 'domain'. We just need to test that the bug works in 5.x as well. It was fixed in 7.3 so that's why we can't do it there.

For **setcookie** we use the new function in 7.3 like so: `setcookie('cross-site-cookie', 'bar', ['samesite' => 'None', 'secure' => true]);` and for earlier versions we have the use header(). I need to test if you can append samesite to 'domain' in setcookie like you can in session_set_cookie_params. If it works then we don't need to manually set the header.

So that's the first part of the problem solved. When it comes to browser support, new browsers need to receive the SameSite value or they won't set the cookie. Old browsers _don't_ receive the SameSite value or they won't set the cookie.

So unsupported browsers get the same cookies as today. And supported browsers get the SameSite cookies.

Funny how a seemingly small update can mess us up so badly. It's going to add a lot of complexity to this library, especially the regex. Might need to be a separate package like you say.

**edit:** i found a site you can use to test the samesite cookie behaviour in different browsers: https://samesite-sandbox.glitch.me/

**Comment by sundayz** [comment]
I found an article that suggests a UA parsing library that looks good, and has an example of a function which checks for samesite browser support:

https://dev.to/zubairmohsin33/dealing-with-chrome-samesite-cookie-attribute-in-shopify-apps-made-with-php-laravel-pcb

Library: https://github.com/jenssegers/agent

**Comment by bryanjhv** [comment]
Sorry for the late reply, been busy at work.
There are lot of things to digest. Thanks for your research.

After evaluating the entire problem, I've come to some other thoughts:
- Let's just focus on supporting browsers, and implement the patches you have in mind.
- User agent sniffing would just introduce so much complexity and make maintainability harder. Also, this library is a session handling library, not a cookie handling one.
- For older browsers, implement the recommended suggestion from https://web.dev/samesite-cookie-recipes/#handling-incompatible-clients (Google). So sorry for older browsers.
- Allow setting `$settings['samesite']` to string (parameter values), `false|null` to disable support, or a `function` returning previous values (if developer wants to user-agent sniff and doesn't like duplicated cookies, let him implement that on his own).

What do you think?

Now, only missing thing is to check where to parse duplicated cookies (and load session), in `__construct` or `startSession`?

NOTE: I didn't go for the user-agent sniffing approach because it's incomplete and hard to implement, for example the link you posted only seems to support Webkit browsers (Firefox fan here!).

**Comment by sundayz** [comment]
Setting two cookies sounds like the perfect solution, I didn't consider it. Good find! If people (for some reason) have very big cookies and don't want to support old browsers, we can add a setting `$settings['disableLegacyCookieSupport']` or similar.

You know the library better than me but I think duplicated cookies should be handled by startSession because other middleware might change the cookie headers. In __construct other middleware hasn't been called yet.

I'm also very busy with work + trying to finish up college so no probs :) Coronavirus really messed up my schedule

**Comment by bryanjhv** [comment]
I'd rather go with the following, because everything is just related to `SameSite` support:

```php
$samesite === true    // 'strict'
$samesite === false   // 'none'
$samesite === null    // (disable)
is_string($samesite)  // (value)
```

For the part about where should it go, it should be noted that it's not about this library but about the way Slim processes middleware. If I remember correctly, they do it down-top, and if it's like that, it will be strictly required that this middleware is registered first before using anything related to sessions, because that's where `startSession` comes in. Problem is: doesn't PHP load session things at the start of the script (before calling `session_start` I mean)? And what would be a use case where session variables are required to be set *before* the middleware is called?

**Comment by bryanjhv** [comment]
After testing some PHP versions using PHPBrew, it looks like at least with PHP 5.4 we can take advantage of that '`path` bug to set the parameter in case it's enabled. There's a need to also chek what would happen if `path` is empty, because if that's the case, the additional `; ` needs to be removed (or it will send a cookie like `value; ; SameSite=Lax`).
Also, I was thinking that maybe it's better to separate (duplicate) those two functions at the top or another file, something like `ss_setcookie` and `ss_session_set_cookie_params` and do the checks for the PHP versions there to avoid including version testing in the core.

**Comment by sundayz** [comment]
I'm not sure if people should ever try to use the session before the middleware is called because that implies they're trying to do it outside of a http request, for something like loading a configuraion file based on what is inside a session. Is that something we want to allow?

Empty path is definitely a good edge case to check for. And I agree that the version checking should be used in a separate function or maybe in another file. I think you could even define a function conditionally so you don't check inside the function.

**Comment by bryanjhv** [comment]
Please give this a try, for now it's just giving basic support:
https://github.com/bryanjhv/slim-session/tree/fb59052746072b7a5598bfe321de22847fa520a4

You should add `'samesite' => '[value]'` to constructor options (it's disabled by default as PHP does).

**Comment by bryanjhv** [comment]
This is fully implemented now.

If the information on https://caniuse.com/#feat=same-site-cookie-attribute is correct regarding:

> This feature is backwards compatible. Browsers not supporting this feature will simply use the cookie as a regular cookie. There is no need to deliver different cookies to clients.

Then there should be no issues at all, and given that many current browsers now support (and even require) this, it defaults to `'Lax'` instead of just being disabled as per PHP's default. If problems arise, then it can be disabled by setting to `''`. This is documented in README.

Many thanks for reporting this.
Feel free to add any comments.
And so sorry for the huge delay.

Versions with support:
- 2.3.0+ for Slim 2.
- 3.7.0+ for Slim 3.
- 4.1.0+ for Slim 4.

**Comment by sundayz** [comment]
Great work! sorry I wasn't able to help out like I said, I've been really busy lately. I appreciate it.

**Comment by boussou** [comment]
There is a version we maintained that manages the samesite attribute.
Code has been ported back from 7.x to 5.6.40
https://github.com/Inducido/php-5.6-with-SameSite/tree/PHP-5.6.40
