### ISSUE TITLE
Error "headers already sent" when testing slim application

### ISSUE THREAD

**Issue by adamgeorgsson** [bryanjhv/slim-session#58]
Hi

I used this middleware with helper for my Slim application and it worked fine when accessing the app from my browser, but not when testing it using phpunit. The error I got was "session_set_cookie_params(): Cannot change session cookie parameters when headers already sent".

I forked this repo (from slim-3 branch) to replicate it with the example code from the readme. The error I got from the fork is slightly different from the error in my own app but I think they are related. The error in the fork is "Cannot modify header information - headers already sent"

My fork: https://github.com/Ejdamm/slim-session/tree/slim-3
I also added the example code in example/index.php so you can try it from browser.

Do you think it could be a bug or is it a usage error?

**Comment by bryanjhv** [comment]
Does this work for you? (like one of Slim core members also does at https://github.com/akrabat/rka-slim-session-middleware/blob/2.0.0/tests/RKATest/SessionMiddlewareTest.php#L88)

```diff
diff --git a/tests/SlimTest.php b/tests/SlimTest.php
index 93125bc..e259d62 100644
--- a/tests/SlimTest.php
+++ b/tests/SlimTest.php
@@ -90,7 +90,7 @@ class SlimTest extends TestCase
         $response = new Response();
 
         // Process the application
-        $response = $this->app->process($request, $response);
+        $response = @$this->app->process($request, $response);
 
         // Return the response
         return $response;
```

Maybe in a future I'll also end up doing:

```diff
diff --git a/tests/HelperTest.php b/tests/HelperTest.php
index 52f3255..d2dd694 100644
--- a/tests/HelperTest.php
+++ b/tests/HelperTest.php
@@ -3,8 +3,6 @@
 use PHPUnit\Framework\TestCase;
 use SlimSession\Helper;
 
-session_start();
-
 class HelperTest extends TestCase
 {
     protected function setUp()
@@ -115,6 +113,7 @@ class HelperTest extends TestCase
      */
     public function testId()
     {
+        session_start();
         $helper = new Helper();
 
         $this->assertSame(session_id(), $helper::id());
@@ -127,6 +126,7 @@ class HelperTest extends TestCase
      */
     public function testDestroy()
     {
+        session_start();
         $helper = new Helper();
 
         $_SESSION = ['a' => 'A', 'b' => 'B', 'c' => 'C'];
```

PS: The second error you got is related to this last patch; given that test are run in alphabetical order, `HelperTest` will run first and execute `session_start` upon loading (which maybe it's my fault, but given it's the only test for now it works), so when it arrives to `SlimTest` and because you don't have a `setUp` which destroys the session, it just tells you that session was already sent.

**Comment by adamgeorgsson** [comment]
Yes it made my tests pass. Thanks for the tip!
